"Items"
{
	"item_searing_flame_of_prometheus"
	{
		"levelRequired"	"20"
		"spellPower"	"0"
		"healingPower"	"322"
		"Multiplier"	"35"
	}

	"item_wraithblade"
	{
		"levelRequired"	"200"
		"warRestricted"	"true"
		"spellPower"	"600"
		"healingPower"	"600"
		"Multiplier"	"0"
	}

	"item_gemstone_key"
	{
		"professionRequired"	"Jewelcrafting"
	}

	//Need to Restrict for
	//Level
	//Class
	//Profession

	//Item Drops should be a different table
}