"Spawns"
{
	"GoblinArea"
	{
		"npc_goblin"
		{
			"Name"			"npc_goblin"
			"RespawnTime"	"2"
			"MaxSpawn"		"9"
			"GoldBounty"	"322"
			"MatBounty"		"420"
		}

		"npc_shaman"
		{
			"Name"			"npc_shaman"
			"RespawnTime"	"5"
			"MaxSpawn"		"3"
			"GoldBounty"	"322"
			"MatBounty"		"4200"
		}
	}

	"BanditArea"
	{
		"npc_bandit"
		{
			"Name"			"npc_bandit"
			"RespawnTime"	"1"
			"MaxSpawn"		"25"
			"GoldBounty"	"322"
			"MatBounty"		"420"
		}
	}
}