"Drops"
{
	"npc_demon_imp"
    { 
		"1"
        {
            "ItemSets"
            {
                "1" "item_ares_bloodthirsty_spear"
                "2" "item_blazing_sword_of_helios"
                "3" "item_immortal_armor_of_hephaestus"
            }
            "Chance"   "100" //of dropping 1 of the set
        }
        "2"
        {
            "Item"     "item_thundering_hammer_of_zeus"
            "Chance"   "100"
            "Multiple" "1"
        }
    }
}